
name: Build and test of Reactive Java Project

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
        - name: Instalar Java 11
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: 11
        - name: Mave Package
          run: mvn -B package --file pom.xml
        - name: Maven Verify
          run: mvn -B clean verify
